[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ConjugatePriors = "1624bea9-42b1-5fc1-afd3-e96f729c8d6c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Particles = "ac9dd01a-757f-5730-a52a-02349aa05ab3"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StatPlots = "60ddc479-9b66-56df-82fc-76a74619b69c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Underscore = "16dbe556-7b29-507b-9ccd-c5dea076dc19"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
